<!DOCTYPE html>
<html>
<head>
  <title>Rumah Besar</title>
  <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
</head>
<body>
    <a-scene inspector="" keyboard-shortcuts="" screenshot="" vr-mode-ui="" device-orientation-permission-ui="">


        <a-sky color="#87CEEB" material="color: #000000" geometry="" position="0 1.01 0" scale="-1 0.9 1"></a-sky>
        
    
        <a-plane position="-4.33947 0.0002 -0.27032" rotation="-90 0 0" width="100" height="100" color="#C0C0C0" material="color: #065c00" geometry="" scale="0.86 1.17 0.00001"></a-plane>
    
    
        <a-entity position="">
    
    
          <a-box position="0.28035 13.17016 12.18894" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.79 0.28 -0.82" rotation="6.18 0 0">
            <a-text value="Pondasi" align="center" position="34.2872 -1.67 7.46657" color="#FFFFFF" scale="7.27 1.75 4" text="value: Lantai"></a-text>
          </a-box><a-box position="8.5 0.54527 0" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="1.46 1.04 1.07">
            <a-text value="Pondasi" align="center" position="0 0.22193 7.62506" color="#FFFFFF" scale="2.23 2.97 4" text=""></a-text><a-text value="Pondasi" align="center" position="3.88 2.46478 7.62506" color="#FFFFFF" scale="2.23 2.97 4" text="value: 2113025001"></a-text>
          </a-box><a-box position="8.5 -0.27473 7.46" width="20" height="1" depth="15" color="#CD853F" material="color: #837d77" geometry="" scale="1.46 1.04 1.07">
            <a-text value="Pondasi" align="center" position="0 1.2 0" color="#FFFFFF" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="6.26843 -6.30545 -40.77394" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.18 1 0.16">
            <a-text value="Pondasi" align="center" position="0 1.2 176.39728" color="#FFFFFF" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="16.8416 -2.70787 -49.45338" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.26 0.82 -0.33">
            <a-text value="Pondasi" align="center" position="0 1.2 0" color="#FFFFFF" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="18.26843 6.23455 6.34517" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.18 1 0.16">
            <a-text value="Pondasi" align="center" position="-0.18 3.3 5.07818" color="#FFFFFF" scale="9.17 2 4" text="value: Jendela; color: #000000"></a-text>
          </a-box><a-box position="18.26843 16.41455 6.34517" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.18 1 0.16">
            <a-text value="Pondasi" align="center" position="0 1.2 0" color="#FFFFFF" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="9.87843 6.27455 6.34517" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.18 1 0.16">
            <a-text value="Pondasi" align="center" position="-61.43452 11.01677 4.5" color="#FFFFFF" scale="14.61 4 4" text="value: Atap"></a-text>
          </a-box><a-box position="9.87843 16.58455 6.34517" width="20" height="1" depth="15" color="#CD853F" material="" geometry="" scale="0.18 1 0.16">
            <a-text value="Pondasi" align="center" position="0 1.2 0" color="#FFFFFF" scale="4 4 4" text=""></a-text>
          </a-box>
    
    
          <a-box position="0.1 4.69 0" width="18" height="7" depth="13" color="#B0E0E6" material="color: #b434ef; emissive: #000000" geometry="" scale="0.59 3.33 1.08">
            <a-text value="Lantai Bawah" align="center" position="0 -1.08 0.46268" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="0 -7.84599 -57.16474" width="18" height="7" depth="13" color="#B0E0E6" material="color: #e99848" geometry="" scale="0.2 0.07 1.06">
            <a-text value="Lantai Bawah" align="center" position="0 6.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="9.7 -19.71 -76.80211" width="18" height="7" depth="13" color="#B0E0E6" material="color: #6e7577" geometry="" scale="1 1.6 1.06">
            <a-text value="Lantai Bawah" align="center" position="0 6.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box>
    
    
          <a-box position="13.95071 3.92525 0.02268" width="15" height="7" depth="10" color="#B0E0E6" material="color: #9e2dd2" geometry="" scale="1.13 6.55 1.38" rotation="">
            <a-text value="Lantai Atas" align="center" position="-0.02439 2.39 3.49481" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="5.996 -4.49 -38.33153" width="15" height="7" depth="10" color="#B0E0E6" material="color: #e99848" geometry="" scale="0.23 0.09 0.25">
            <a-text value="Lantai Atas" align="center" position="0 13.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="-5.99587 -4.36 -43.60183" width="15" height="7" depth="10" color="#B0E0E6" material="color: #e89847" geometry="" scale="0.23 0.09 0.25">
            <a-text value="Lantai Atas" align="center" position="0 13.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="0 -16.13005 -57.50604" width="15" height="7" depth="10" color="#B0E0E6" material="color: #af6703" geometry="" scale="1.28 0.12 1.46">
            <a-text value="Lantai Atas" align="center" position="0 13.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="-2.059 -8.569 -58.67912" width="15" height="7" depth="10" color="#B0E0E6" material="color: #ae6602" geometry="" scale="0.5 -0.04 0.58" rotation="40 -90 0">
            <a-text value="Lantai Atas" align="center" position="143.63544 277.41811 221.70532" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="2.05931 -7.43859 -57.22429" width="15" height="7" depth="10" color="#B0E0E6" material="color: #b36906" geometry="" scale="0.5 -0.04 0.58" rotation="40 90 0">
            <a-text value="Lantai Atas" align="center" position="-76.05024 -31.69189 -37.66877" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="13.06978 28.98598 4.80557" width="15" height="7" depth="10" color="#B0E0E6" material="color: #7d7361" geometry="" scale="1.34 -0.08 1.26" rotation="-40 -180 0">
            <a-text value="Lantai Atas" align="center" position="0 -62.98524 -90.79404" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="13.06978 28.98598 -4.31556" width="15" height="7" depth="10" color="#B0E0E6" material="color: #5c5447" geometry="" scale="1.34 -0.11 1.22" rotation="-40 0 0">
            <a-text value="Lantai Atas" align="center" position="0 13.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="16.829 -12.298 -46.87129" width="15" height="7" depth="10" color="#B0E0E6" material="color: #b36a07" geometry="" scale="1.05 0.05 1.2" rotation="40 0 0">
            <a-text value="Lantai Atas" align="center" position="0 -64.33029 -92.39701" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="-0.86198 18.25788 5.11381" width="15" height="7" depth="10" color="#B0E0E6" material="color: #5f5749" geometry="" scale="0.85 -0.05 1.34" rotation="40 0 0">
            <a-text value="Lantai Atas" align="center" position="0 -129.08102 169.56392" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="-0.852 18.218 -4.984" width="15" height="7" depth="10" color="#B0E0E6" material="color: #494238" geometry="" scale="0.85 -0.05 1.34" rotation="40 180 0">
            <a-text value="Lantai Atas" align="center" position="0 13.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box><a-box position="18.25979 23.77433 1.7778" width="15" height="7" depth="10" color="#B0E0E6" material="color: #32b3b1" geometry="" scale="0.31 3.54 0.44">
            <a-text value="Lantai Atas" align="center" position="0 13.2 0" color="#000000" scale="4 4 4" text=""></a-text>
          </a-box>
    
    
          <a-cone position="18.24152 38.02671 1.75548" radius-bottom="10" radius-top="0" height="10" color="#CD5C5C" material="color: #038312" geometry="" scale="-0.39 0.53 -0.39">
            <a-text value="Atap" align="center" position="-39.40611 10.99287 28.91521" color="#FFFFFF" scale="4 4 4" text="" rotation="0 180 0"></a-text>
          </a-cone>
    
    
          
    
    
          
          <a-box position="0 -20.28 -42.22923" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="">
            <a-text value="Jendela" align="center" position="0 6.55408 48.69983" color="#000000" scale="4 4 4" text="value: Atap"></a-text>
          </a-box><a-box position="-6.00164 -17.41 -38.53748" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="">
            <a-text value="Jendela" align="center" position="6.18009 27.48381 45.62565" color="#000000" scale="4 4 4" text="value: Dinding"></a-text><a-text value="Jendela" align="center" position="20.17009 21.56381 46.37565" color="#000000" scale="4 4 4" text="value: Aysetu Sindana Mahia Kaputri; color: #ffffff"></a-text>
          </a-box>
          <a-box position="-6.23 -10.011 -39.40756" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1 2.38 1">
            <a-text value="Jendela" align="center" position="6.30434 0.56785 46.73364" color="#000000" scale="4 2.46 4" text="value: Pintu; color: #ffffff"></a-text>
          </a-box>
          <a-box position="0.17 4.369 7.05235" width="3" height="3" depth="0.2" color="#808080" material="color: #660000" geometry="" scale="1 2.38 1">
            
          </a-box><a-box position="-3.51 -3.181 -55.57255" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1.5 1.69 0.81">
            
          </a-box><a-box position="3.51 -12.41126 -59.93814" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1.5 1.69 0.81">
            
          </a-box><a-box position="18.22 9.87874 6.95163" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1 2.38 1">
            
          </a-box><a-box position="18.22 20.19874 6.95163" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1 2.38 1">
            
          </a-box><a-box position="9.9 10.02874 6.95163" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1 2.38 1">
            
          </a-box><a-box position="9.9 20.27874 6.95163" width="3" height="3" depth="0.2" color="#808080" material="color: #ffffff" geometry="" scale="1 2.38 1">
            
          </a-box>
    
    
          <a-entity position="0 11.42 0">
            <a-cylinder position="0.05812 -16.93844 -52.40567" radius="1" height="10" color="#8B4513" material="" geometry="" scale="1 1.97 1" rotation="0 90 90"></a-cylinder><a-cylinder position="15.01899 -16.96523 -42.47041" radius="1" height="10" color="#8B4513" material="" geometry="" scale="1 1.97 1" rotation="0 0 90"></a-cylinder>
            <a-cylinder position="18.16131 -75.88076 -57.81673" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 1 0.5"></a-cylinder>
            <a-cylinder position="-5.06523 -8.961 6.63122" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 2.86 0.5"></a-cylinder><a-cylinder position="-5.06523 -12.771 14.96517" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 2.86 0.5"></a-cylinder><a-cylinder position="-0.07126 4.91693 6.64122" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 1.1 0.5" rotation="90 90 0"></a-cylinder><a-cylinder position="22.40724 -8.9609 6.63122" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 4.87 0.5"></a-cylinder><a-cylinder position="5.12219 -8.9609 6.63122" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 4.88 0.5"></a-cylinder><a-cylinder position="5.12219 -22.9609 14.91281" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 4.88 0.5"></a-cylinder>
            <a-cylinder position="18.161 -24.63266 -67.79526" radius="1" height="10" color="#8B4513" material="" geometry="" scale="0.5 1 0.5"></a-cylinder>
          </a-entity>
    
    
          <a-triangle position="-4.69 19.329 0.16033" rotation="0 -90 0" width="15" height="15" material="color: #CD853F" geometry="" scale="13.93 5.84 1.44"></a-triangle><a-triangle position="5.67 29.68328 0.08033" rotation="0 -90 0" width="15" height="15" material="color: #CD853F" geometry="" scale="13.93 5.84 1.44"></a-triangle><a-triangle position="21.79521 29.56961 0.14827" rotation="0 90 0" width="15" height="15" material="color: #CD853F" geometry="" scale="13.72 5.7 1.44"></a-triangle><a-triangle position="17.97979 20.02131 -31.63148" rotation="0 -180 0" width="15" height="15" material="color: #CD853F" geometry="" scale="19.41 8.06 1.44"></a-triangle>
    
        </a-entity>
    
    
        <a-entity camera="" position="7.953674344843896 13.643543029697797 32.487041690485185" look-controls="" wasd-controls="fly: true" rotation="-8.823550045014677 0.6875493541569191 0" data-aframe-inspector-original-camera=""></a-entity>
        
      <div class="a-loader-title" style="display: none;">Rumah Besar</div><div class="a-loader-title" style="display: none;">Rumah Besar</div></a-scene>
</body>
</html>
